language: node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm run-script lint
 - npm run-script test
 - npm run coverage

# Send coverage data to Coveralls
after_script: "nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js"
